version: '3.4'

networks: 
  dev:
    driver: bridge

services:
  nginx:
    container_name: nginx
    depends_on:
      - demo-app
      - react-app
    build:
      dockerfile: Dockerfile
      context: "D:/PatientPortal2/Hosptial_React-master/"
    ports:
      - 80:80

  demo-app:
    image: docker.io/library/patientdemo  
    
    container_name: hospitalapp-services
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:slayervsdrow@app_db:5432/hospital_api
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=DhftOS5uphK3vmCJQrexST1RsyjZBjXWRgJMFPU4
      - ALGORITHM=HmacSha256
    depends_on:
      - app_db
    networks:
      - dev
    

  app_db:
    image: postgres:latest
    container_name: hospital_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=slayervsdrow
      - POSTGRES_DB=hospital_api
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - "5050:80"
    depends_on:
      - app_db
    networks:
      - dev

  react-app:
    image: react-patientportal:latest
    container_name: React-JS
    ports:
      - "3000:3000"
    build:
      context: "D:/PatientPortal2/Hosptial_React-master/"
      dockerfile: Dockerfile
    networks:
      - dev

volumes:
  app_data:
